[package]
name = "arjunpatil5666/scramjet-proxy"
version = "0.1.0"
description = "Scramjet proxy running on Wasmer Node"

[[command]]
name = "run"
module = "wasmer/node:node"
runner = "https://webc.org/runner/wasi"

[deploy]
[[deploy.backend]]